kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config-workflow
  labels:
    k8s-app: fluentd-logging
    version: v1
data:
  fluent.conf: |
    <system>
      rpc_endpoint 127.0.0.1:24444
    </system>

    <source>
      @type tail
      path "/opt/app/log.log"
      pos_file "/opt/app/file.log.pos"
      tag "#{ENV['WORKFLOW_ID'] || 'default-id'}"
      read_from_head true
      refresh_interval 1
      <parse>
        @type none
      </parse>
    </source>

    <filter **>
        @type record_transformer
        enable_ruby
        <record>
          time ${Time.now.strftime('%Y-%m-%dT%H:%M:%S%z')}
        </record>
      </filter>

    <match **>
      @type opensearch
      @id out_os
      @log_level info
      include_tag_key true
      host opensearch-cluster-master
      port 9200
      index_name workflow_log
      <buffer>
        flush_at_shutdown true
        flush_mode immediate
        flush_thread_count 8
        flush_thread_interval 1
        flush_thread_burst_interval 1
        retry_forever true
        retry_type exponential_backoff
      </buffer>
    </match>
